### ISSUE TITLE
[Feature request] Add to NPM

### ISSUE THREAD

**Issue by HarryBurns** [umpirsky/currency-list#11]
Your repo is missing in NPM.
Please, add package.json manifest file and add it to [NPM](https://www.npmjs.com/) repository

**Comment by umpirsky** [comment]
Thanks for reporting. We should add something similar to https://github.com/umpirsky/country-list/blob/master/package.json, if someone has time to contribute and speed things up, PR-s are welcome.

**Comment by HarryBurns** [comment]
Done: https://github.com/umpirsky/currency-list/pull/12

But you still need to up version a bit in package.json and make new github release. Thanks ^_^

**Comment by umpirsky** [comment]
New version released, thanks!

**Comment by HarryBurns** [comment]
But package.json will allow us to install your package via NPM by direct link.

And if you want your packages to be searchable via npm repository by "@umpirsky/currency-list" - you should register your projects on https://www.npmjs.com manually.

**Comment by umpirsky** [comment]
I discourage people to use this package via npm, that's why I don't submit it there. Simply because the package is huge.
